### ISSUE TITLE
GUI 디자인 설계

### ISSUE THREAD

**Issue by kairos03** [Team-J11/BaramItemManager#1]
GUI 디자인을 설계해야함
@goldragoon @gtw04

**Comment by kairos03** [comment]
추가 필요
![kakaotalk_20160828_163758780](https://cloud.githubusercontent.com/assets/6357456/18039084/50df0d7e-6dda-11e6-90fe-01b147d42d2e.png)

**Comment by kairos03** [comment]
설계 되었나요?

**Comment by goldragoon** [comment]
아직이요, 오늘 저녁먹고 커밋할게요 ^^ 고객님.

**Comment by goldragoon** [comment]
![screenshot from 2016-09-01 20-47-12_edit](https://cloud.githubusercontent.com/assets/2537598/18166564/d7b38b0a-7086-11e6-8f66-0ee6aaf446e5.png)

추가 사항
1. 불러오기 버튼도 굳이 안눌러도 되도록, 왼쪽 리스트 누르면 바로 불러와지게. 그러나 현재 아이템의 속성을 한개라도 수정했을 경우 저장 경고창 띄우기.
2. 그리고 현재 수정하고 있는 아이템이 뭔지 맨위에 표시, multiselect 가능하게 해서 여러 아이템 동시에 수정 가능하게 만들것임.
